apiVersion: backstage.io/v1alpha1
kind: Alias
metadata:
  name: oss-backstage-alias
  description: Alias upon oss backstage
spec:
  owner: sarabadu
  target: https://github.com/Sarabadu/backstage-override/blob/main/external-org.yml
  overrides:
    metadata:
      namespace: ext
    spec:
      memberOf: team-a
